USE [master]
GO
/****** Object:  Database [music]    Script Date: 28.02.2024 9:00:17 ******/
CREATE DATABASE [music]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'music', FILENAME = N'C:\Users\fedor\desktop-4jepinrlocaldb#b4f5c479.master.dbo' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'music_log', FILENAME = N'C:\Users\fedor\desktop-4jepinrlocaldb#b4f5c479.dbo' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [music] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [music].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [music] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [music] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [music] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [music] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [music] SET ARITHABORT OFF 
GO
ALTER DATABASE [music] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [music] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [music] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [music] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [music] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [music] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [music] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [music] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [music] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [music] SET  DISABLE_BROKER 
GO
ALTER DATABASE [music] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [music] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [music] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [music] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [music] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [music] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [music] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [music] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [music] SET  MULTI_USER 
GO
ALTER DATABASE [music] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [music] SET DB_CHAINING OFF 
GO
ALTER DATABASE [music] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [music] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [music] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [music] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [music] SET QUERY_STORE = OFF
GO
ALTER DATABASE [music] SET  READ_WRITE 
GO
